-- Enter migration here

DROP TABLE IF EXISTS messages cascade;

CREATE TABLE messages(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content VARCHAR NOT NULL
);

INSERT INTO messages(content) VALUES ('my balls');
INSERT INTO messages(content) VALUES ('message two');

